# Generated by Django 2.2.5 on 2019-09-12 13:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190912_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='request',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='uploaded',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 12, 13, 39, 21, 207217)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='Submitted_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 12, 13, 39, 21, 207667)),
        ),
        migrations.CreateModel(
            name='Assignment_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.BooleanField(default=False)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentt', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='requestt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestt', to='core.Assignment_Request'),
        ),
    ]
