# Generated by Django 2.2.5 on 2019-09-13 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190912_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='uploaded',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 5, 20, 20, 261324)),
        ),
        migrations.AlterField(
            model_name='assignment_request',
            name='request',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='Submitted_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 5, 20, 20, 261748)),
        ),
    ]
