# Generated by Django 2.2.5 on 2019-09-13 09:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190913_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='uploaded',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 9, 41, 51, 960638)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='Submitted_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 9, 41, 51, 961049)),
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, max_length=25, null=True)),
                ('star5', models.CharField(blank=True, max_length=15, null=True)),
                ('star4', models.CharField(blank=True, max_length=15, null=True)),
                ('star3', models.CharField(blank=True, max_length=15, null=True)),
                ('star2', models.CharField(blank=True, max_length=15, null=True)),
                ('star1', models.CharField(blank=True, max_length=15, null=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.Submission')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentss', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
