# Generated by Django 2.2.5 on 2019-09-13 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190913_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remark',
            name='star1',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='star2',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='star3',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='star4',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='star5',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='uploaded',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 10, 10, 58, 139370)),
        ),
        migrations.AlterField(
            model_name='remark',
            name='rating',
            field=models.CharField(blank=True, choices=[('1star', '1star'), ('2star', '2star'), ('3star', '3star'), ('4star', '4star'), ('5star', '5star')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='Submitted_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 13, 10, 10, 58, 139812)),
        ),
    ]
